spring:
  application:
    name: mongo-elasticsearch-v1
  data:
    mongodb:
      uri: mongodb+srv://usrnm:psswrd@clustrnm.qfnan.mongodb.net/?retryWrites=true&w=majority&appName=clustrnm
      database: Products
